### ISSUE TITLE
Error installing v0.8 from PyPI

### ISSUE THREAD

**Issue by naktinis** [Parisson/TimeSide#104]
Produces the following error:

```
Collecting TimeSide==0.8 (from -r requirements.txt (line 2))
Using cached TimeSide-0.8.tar.gz
  Complete output from command python setup.py egg_info:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-h26sb9iv/TimeSide/setup.py", line 74, in <module>
      install_requires=get_dependencies('environment.yml'),
    File "/tmp/pip-build-h26sb9iv/TimeSide/setup.py", line 20, in get_dependencie
      with open(env_yml_file, 'r') as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'environment.yml'
```

If you look at [TimeSide-0.8.tar.gz](https://pypi.python.org/packages/4e/6d/d15cfb7e01e05ee7ab421f9925222f426fbc27e4933b41a8c5f36e2fba69/TimeSide-0.8.tar.gz), there is no `environment.yml`, although it is present in https://github.com/Parisson/TimeSide/tree/0.8

Installing v0.7.1 works just fine.

**Comment by yomguy** [comment]
Thanks @naktinis for the report! It will be fixed in the next release 0.8.1 coming (very) soon.
