### ISSUE TITLE
Tensorboard access

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#108]
It is possible to launch the ```tensorboard``` of ```tensorflow``` from the bash : 

```
(base) root@1ebbf0f4034a:/srv/media/notebooks# tensorboard --logdir=output
TensorBoard 1.9.0 at http://1ebbf0f4034a:6006 (Press CTRL+C to quit)
```
but how to access it from the browser or launch it via a script, like a notebook ?

**Comment by yomguy** [comment]
Hi @AnasGhrab 
Good idea! You should share the container port from the .yml composition file:
```
app:
  ports:
    - "6006:6006"
    - ...
```
and then browse http://localhost:6006/

**Comment by yomguy** [comment]
added as a container in #fe091a1, start it with:
`docker-compose -f docker-compose -f env/tensorboard.yml` and browser http://localhost:6006
