### ISSUE TITLE
Jupyter notebook + Telemeta public access

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#110]
When lauching the _jupyter notebook_ with this command : 
``sudo docker-compose -f docker-compose.yml -f env/notebook.yml up``

the public interface becomes inaccessible, giving an error ``502 Bad Gateway``. Is it a problem in my nginx server configuration ?

```
telemeta@projets:~/Telemeta$ sudo docker-compose ps
      Name                     Command               State                 Ports              
----------------------------------------------------------------------------------------------
telemeta_app_1      /srv/app/bin/notebook.sh         Up       8000/tcp, 0.0.0.0:9999->9999/tcp
telemeta_broker_1   docker-entrypoint.sh redis ...   Up       6379/tcp                        
telemeta_data_1     true                             Exit 0                                   
telemeta_db_1       docker-entrypoint.sh mysql ...   Up       3306/tcp, 33060/tcp             
telemeta_nginx_1    nginx -g daemon off;             Up       0.0.0.0:8000->80/tcp            
telemeta_search_1   /docker-entrypoint.sh elas ...   Up       9200/tcp, 9300/tcp              
telemeta_worker_1   /bin/bash bin/worker.sh          Up       8000/tcp    
```

Without the notebook, ``sudo docker-compose up -d``, everything is all right.

**Comment by yomguy** [comment]
Hi @AnasGhrab !
Sorry for my late reply.. I am now back into the game with @Tointoin aka Antoine Grandry to develop TimeSide in the context of the WASABI project.
I cannot reproduce the bug : I can browse the notebook app at http://localhost:8888 
Are you using this port?
Cheers

**Comment by AnasGhrab** [comment]
My question : Is it possible to have access to the port 80 (or 8000) and 8888 and the same time ? It doesn't work for my.
