### ISSUE TITLE
Add Processor.version to core API

### ISSUE THREAD

**Issue by yomguy** [Parisson/TimeSide#111]
As every plugins need to be versioned, we need to add a `version` property to `core.processor.Processor`, `core.api.IProcessor` and `server.models.Processor`.
To satisfy this new api constraint, every single existing plugin - core, internal and external ones - will need to be adapted.

**Comment by Tointoin** [comment]
what to do of processors with undefined `version` property? Set them to an arbitrary value like `"1"`or `"0.1"`?

**Comment by yomguy** [comment]
Sorry @Tointoin for my late reply. `1.0` by default then.
