### ISSUE TITLE
[server] add Result.run_time as a FloatField

### ISSUE THREAD

**Issue by yomguy** [Parisson/TimeSide#114]
The field should content the run time of the pipe.run() of a Item.run().

**Comment by Tointoin** [comment]
is Django's durationField interesting for this case?

https://docs.djangoproject.com/fr/2.2/ref/models/fields/#durationfield

**Comment by yomguy** [comment]
yes good idea @Tointoin !

**Comment by Tointoin** [comment]
> is Django's durationField interesting for this case?
> 
> https://docs.djangoproject.com/fr/1.10/ref/models/fields/#durationfield

DurationField is actually not usefull and requires python's datetime module (with hour, minute, second, microsecond et time zone attributs).  Time module is enough for our usecase. Moreover I am not sure that DurationField would fit time weighting with file's duration. I hence keep FloatField.

**Comment by Tointoin** [comment]
https://stackoverflow.com/questions/51638173/why-does-a-django-postgres-migration-altering-field-to-durationfield-causes-an-e
