### ISSUE TITLE
[server] run_time set to None while running same analyzer twice with one as parent

### ISSUE THREAD

**Issue by Tointoin** [Parisson/TimeSide#115]
This happens for instance while running timeside-create-boilerplate django command with docker. One run all presets on all Test items. The outcome is not fully reproductible. Each time, at least for spectrogram_analyzer preset, all results have a None run_time. Sometimes also for loudness_itu, aubio_silence or essentia_dissonance.

It happens also with only one Item, (example : singleton experience with C4_Scale) while calling in the same experience spectrogram_analyzer and spectrogram presets. Spectrogram is a grapher wich has spectrogram_analyzer as parent.

**Comment by Tointoin** [comment]
Does it after all makes sens to have twice the same preset in the same experience : once as a parent, once directly called? @yomguy

**Comment by yomguy** [comment]
> Does it after all makes sens to have twice the same preset in the same experience : once as a parent, once directly called? @yomguy

Sorry for not replying in time @Tointoin. It definitely does not make sens at all!
