### ISSUE TITLE
Upgrade to Python 3.7

### ISSUE THREAD

**Issue by yomguy** [Parisson/TimeSide#116]
- [x] core (@piem)
- [x] server (@Tointoin)
- [x] upgrade env docker and deps (@yomguy)
- [x] update .travis.yml to get py3.7 (@yomguy )

**Comment by Tointoin** [comment]
Celery 4.3 is not Python 3.8 compatible. We have to wait for next Celery version before upgrading to Python 3.8

**Comment by yomguy** [comment]
@Tointoin OK for python 3.7 included in Debian Buster.
