### ISSUE TITLE
[server] schema/doc/serializers: replace serializers.MethodField with Serializer class

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#149]
Currently, MethodSerializers are used to return dicts.
For example, in [`audio_url`](https://github.com/Parisson/TimeSide/blob/feature/next/timeside/server/serializers.py#L75) and [`waveform`](https://github.com/Parisson/TimeSide/blob/feature/next/timeside/server/serializers.py#L139). Other occurrences may exist.

The issue with this technique is that the auto-generated schema do not have knowledge of the return type of the method. So, in the schema, MethodFields have a string type.
e.g waveform is a string
https://sandbox.wasabi.telemeta.org/timeside/redoc/#operation/RetrieveItem

In order to workaround this, we should use [nested serializers](https://www.django-rest-framework.org/api-guide/serializers/#dealing-with-nested-objects).
In order to keep the initial implementation, the `.to_representation` of the serializer method can be overridden.

**Comment by Tointoin** [comment]
How to pass serializer's model `item` as argument  such as `obj` argument of `SerializerMethodField` would do in a `HyperlinkedModelSerializer` ?

```python
class WaveformSerializer(serializers.Serializer):
    """Populate waveform"""
    ... # Fields definition
    def __init__(self, item):
        self.item = item
    def to_representation(self, instance):
        ...
        do_something_with(self.item)
        ...
class ItemWaveformSerializer(ItemSerializer):
    class Meta:
        model = ts.models.Item
    waveform = WaveformSerializer(ITEM_NEEDED)
```

**Comment by gnuletik** [comment]
Thanks for this @Tointoin !

However, it seems that the schema export the `min_values` and `max_values` (from the `WaveformSerializer`).
Should it be replaced with `min` and `max` ?
