### ISSUE TITLE
[server] schema/doc/serializers: duplicate retrieveItem operationId

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#150]
In the schema (and by extension, the documentation), there is a duplicated operationId `retrieveItem` :
- https://sandbox.wasabi.telemeta.org/timeside/redoc/#operation/retrieveItem
- https://sandbox.wasabi.telemeta.org/timeside/redoc/#operation/RetrieveItem (should be RetrieveWaveform)

Those operationId are auto-generated by the Django Rest Framework with [the `_get_operation_id` method](https://github.com/encode/django-rest-framework/blob/4137ef41efa77bd404bdc078159081740abdf930/rest_framework/schemas/openapi.py#L104).
[As the `ItemWaveView` class uses the `Item` model](https://github.com/Parisson/TimeSide/blob/a005e307093753cafa8fb82efe07a7318605fd5e/timeside/server/views.py#L106), the `RetrieveItem` operation id is used.

Currently, I can't see any valid solution to this. We may need to wait for DRF to add an attribute allowing us to override the name used in the operation.

**Comment by gnuletik** [comment]
This PR has been merged into the master branch of DRF : https://github.com/encode/django-rest-framework/pull/7208
So we can now fix this issue :)

**Comment by yomguy** [comment]
great! congrats @gnuletik!
I propose to let this issue open until the next release of DRF.
