### ISSUE TITLE
[server] views.ItemTranscode.get has a recursive loop

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#159]
If the task runner is not up or cannot process a task, a recursive loop occurs.
It triggers the following error :

```
RuntimeError at
/timeside/api/items/3580dff6-a705-46a4-8fee-fcb945247ed0/download/mp3
maximum recursion depth exceeded
```
We can fix it by: 
- Replacing the recursion with a `while` loop
- Checking the TaskStatus instead of waiting for a DB row creation

**Comment by Tointoin** [comment]
There is already a `while` loop on `task.status` in `task.run(wait=True)` statement.

Solutions could be replacing `get_or_create` statements with:
- `try...except` as [in this example](https://github.com/Ircam-Web/mezzanine-organization/blob/master/organization/core/backend.py)
- [`get_fist_or_create`](https://github.com/Parisson/TimeSide/blob/35e8fd501b450dfa0b48b821271fcefb413552b0/timeside/server/models.py#L176)
