### ISSUE TITLE
[server] Wasabi sandbox server: duplicated singleton selections

### ISSUE THREAD

**Issue by Tointoin** [Parisson/TimeSide#161]
Following urls return the same error:

```log
File "/srv/lib/timeside/timeside/server/serializers.py" in to_representation
  171.         result = get_or_run_proc_result('waveform_analyzer', item=instance)

File "/srv/lib/timeside/timeside/server/utils.py" in get_or_run_proc_result
  29.                                                         selection=item.get_single_selection())

File "/srv/lib/timeside/timeside/server/models.py" in get_single_selection
  449.             description=sel_description)

File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py" in manager_method
  82.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py" in get_or_create
  538.             return self.get(**kwargs), False

File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py" in get
  412.             (self.model._meta.object_name, num)

Exception Type: MultipleObjectsReturned at /timeside/api/items/07836d4f-72d0-4a66-a076-f6f06cce572c/waveform/
Exception Value: get() returned more than one Selection -- it returned 2!
```

- [sandbox.wasabi...../download/mp3](https://sandbox.wasabi.telemeta.org/timeside/api/items/f31f1889-6c89-4ca8-a538-514c78d7aae6/download/mp3)
- [sandbox.wasabi...../download/ogg](https://sandbox.wasabi.telemeta.org/timeside/api/items/f31f1889-6c89-4ca8-a538-514c78d7aae6/download/ogg)
- [sandbox.wasabi...../waveform/](https://sandbox.wasabi.telemeta.org/timeside/api/items/07836d4f-72d0-4a66-a076-f6f06cce572c/waveform/)

- [x] Remove all `get_single_selection` method and its calls
- [x] Remove data that is inconsistent due to this bug

(Reported by @gnuletik).

**Comment by Tointoin** [comment]
`/waveform/` urls raise now follwing error:

```
File "/srv/lib/timeside/timeside/server/serializers.py" in to_representation
  175.         wav_res = h5py.File(result.hdf5.path, 'r').get(result_id)

File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/files.py" in path
  56.         self._require_file()

File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/files.py" in _require_file
  38.             raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)

Exception Type: ValueError at /timeside/api/items/07836d4f-72d0-4a66-a076-f6f06cce572c/waveform/
Exception Value: The 'hdf5' attribute has no file associated with it.
```

**Comment by Tointoin** [comment]
> `/waveform/` urls raise now follwing error:
> 
> ```
> ...
> Exception Type: ValueError at /timeside/api/items/07836d4f-72d0-4a66-a076-f6f06cce572c/waveform/
> Exception Value: The 'hdf5' attribute has no file associated with it.
> ```
Removing all results with `draft`status resolves it (here only mp3/ogg encode and waveform analysis).

**Comment by gnuletik** [comment]
Hi @Tointoin,

Sorry to reopen but I just had the issue recently on this item: https://sandbox.wasabi.telemeta.org/timeside/api/items/f819b56c-e4c4-4762-83ac-77eb81084268/download/mp3

**Comment by Tointoin** [comment]
Hi @gnuletik, recent commit for [#159 recursive loop](https://github.com/Parisson/TimeSide/issues/159) generated this error. It's fixed now, on sandbox also.
