### ISSUE TITLE
could I get the audio's language with the great project ?

### ISSUE THREAD

**Issue by ucas010** [Parisson/TimeSide#168]
hi,dear
If I just want to recongize the audio's language ,
what API should I use ?
Thx

**Comment by yomguy** [comment]
Hi @ucas010, the framework does not embed any language recognition library yet, but it could be nice ! I just can advise you to follow this howto:

https://realpython.com/python-speech-recognition/

and advise you to give a try to pocketsphinx. But all of the library I know need the language as a parameter to be able to decode. I don't know that could discover it automatically. But maybe Vocapia could have something to do with this https://www.vocapia.com/
