### ISSUE TITLE
[server] add a django cleanup command

### ISSUE THREAD

**Issue by yomguy** [Parisson/TimeSide#170]
This command should remove:
- [x] any singleton Selection
- [x] any result without file
- [x] any result file without result pointing to it

Also advisable:
- [x] a result.pre_delete signal that runs `os.remove` on any hdf5 or audio file
- [x] define a workflow to remove a result (a waveform for example)

**Comment by Tointoin** [comment]
>     * [x]  a result.pre_delete signal that runs `os.remove` on any hdf5 or audio file
There is a bug on sandbox instance @yomguy after dealing with `result.pre_delete`.

I explained it on [issue 180](https://github.com/Parisson/TimeSide/issues/180)
