### ISSUE TITLE
[server] Add support for Partial Content (206) HTTP requests

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#171]
As of today, partial content requests do not seems to be supported for mp3 files.

e.g.
```bash
curl -v -r0-1 'https://sandbox.wasabi.telemeta.org/timeside/api/items/26bb3f74-cf9f-4b91-a95b-d12503a64585/download/mp3' > /dev/null 2> >(grep 'HTTP')
```
```
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> GET /timeside/api/items/26bb3f74-cf9f-4b91-a95b-d12503a64585/download/mp3 HTTP/2
< HTTP/2 200 
```
As you can see the HTTP response status code is `200` instead of `206`.

For example :

```
curl -v -r0-1 https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_700KB.mp3 > /dev/null 2> >(grep 'HTTP')
```

```
> GET /wp-content/uploads/2017/11/file_example_MP3_700KB.mp3 HTTP/1.1
< HTTP/1.1 206 Partial Content
```

This leads to different issues : 
- Long files will be long to load
- Seeking on audio elements do not work on Chrome (see https://stackoverflow.com/a/9549404 and https://stackoverflow.com/a/10619435)

Any plans to implement this feature @yomguy @Tointoin ?

**Comment by piem** [comment]
hi @gnuletik 

You might need to enable caching, or add [`proxy_force_ranges on;`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_force_ranges).

my 2¢ :)

**Comment by yomguy** [comment]
> hi @gnuletik
> 
> You might need to enable caching, or add [`proxy_force_ranges on;`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_force_ranges).
> 
> my 2¢ :)

Applied. @gnuletik, could you please test?

**Comment by gnuletik** [comment]
Hi @yomguy,

Thanks for having a look at it ! However, it is not working.
I put the curl command to test the Partial Content request in the original post.

Here's another command with only the response code
```
curl -s -o /dev/null -w '%{http_code}' -r0-1 'https://sandbox.wasabi.telemeta.org/timeside/api/items/26bb3f74-cf9f-4b91-a95b-d12503a64585/download/mp3'
```
It should print `206` but it actually prints `200`

**Comment by yomguy** [comment]
@gnuletik @Tointoin 

This last route trigs the backend to get the X-accel header and then the stream.
If the direct file URL is used, the 206 is well return:

`curl -s -o /dev/null -w '%{http_code}' -r0-1 'https://sandbox.wasabi.telemeta.org/media/results/26bb3f74-cf9f-4b91-a95b-d12503a64585/9613ad56-18d1-444f-a27d-034ace8fdaba.mp3'`

Maybe we should change the default transcoded Item route so that it sends the direct URL of the file. The security would be narrower but the UUID stuff should make it difficult to retrieve any stream coming from the result knowing the item's UUID only.

Nevertheless, I will also try to make it work tweaking the X-Accel stuff... ;)

**Comment by gnuletik** [comment]
Hi @yomguy,
It makes sense!
It would be nice to get the Partial Content working from the API route.

If that's not possible, we can change the ItemSerializer to send the Nginx URLs.
In this case, we may protect the URL with nginx's `ngx_http_secure_link_module` (see https://www.nginx.com/blog/securing-urls-secure-link-module-nginx-plus/).

I think the second approach is more accurate as it leverage more load to nginx and will allow further optimization (we can build the URL even if the app is not behind this nginx instance).
However, I'm afraid we won't have time to change this before the end of the project.

**Comment by yomguy** [comment]
Hi @gnuletik 
Thanks for this proposition. Let's create a new issue for installing and using `ngx_http_secure_link_module`.
Before securing more, I propose @Tointoin that the server return the direct URL of the file so that we can have the Partail Content quickly.

**Comment by yomguy** [comment]
@gnuletik @Tointoin 

Due to https://github.com/Parisson/TimeSide/blob/dev/timeside/server/views.py#L649 the sandbox would return a `FileResponse` instead of the media URL plus the X-Accel header.

Switching the instance to `DEBUG=False` simply resolve the issue:
```
curl -s -o /dev/null -w '%{http_code}' -r0-1 'https://sandbox.wasabi.telemeta.org/timeside/api/items/26bb3f74-cf9f-4b91-a95b-d12503a64585/download/mp3'
206
```
