### ISSUE TITLE
[server / schema] retrieveItemWaveform operation do not have query parameters

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#175]
The `retrieveItemWaveform` operationId in the OpenAPI schema should have 3 query parameters: `start`, `stop`, `nb_pixels`.

None of them are available now.

It seems that a DRF serializer can have a `filterset_class` attribute (see https://www.django-rest-framework.org/api-guide/filtering/).

This attribute should be a django-filter class : https://github.com/carltongibson/django-filter

**Comment by Tointoin** [comment]
![Capture d’écran 2020-04-09 à 18 27 48](https://user-images.githubusercontent.com/22236704/78917938-e63eaa80-7a8f-11ea-8cf5-106f1e606256.png)

???

**Comment by gnuletik** [comment]
The area highlighted in your screenshot is in the "response samples" section.
The `start`, `stop`, and `nb_pixels` properties are also in the response.

From the reDoc point of view, those parameters should appear in the "Query Parameters" section as in the `listItems` operation that you can find here : https://sandbox.wasabi.telemeta.org/timeside/api/docs/#operation/listItems

**Comment by gnuletik** [comment]
Closed through #181
