### ISSUE TITLE
[server] ImproperlyConfigured at /timeside/api/analysis/

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#178]
https://sandbox.wasabi.telemeta.org/timeside/api/analysis/

```
Could not resolve URL for hyperlinked relationship using view name "subprocessor-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```

**Comment by Tointoin** [comment]
The issue was caused by [this commit](https://github.com/Parisson/TimeSide/commit/c6de1f0f0b006d1737d8a4b667779d9165e2667c#diff-35c8ecedb0c2e662f1f26e4d7a38606b):
I thought was not usefull to be available through api but it is indeed needed as a lookup field for analysis. My bad!
