### ISSUE TITLE
[server/prod] Server returns 500 error on wasabi.telemeta.org

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#185]
When loading the following page :
https://wasabi.telemeta.org/timeside/items/e3608545-b122-47cb-87d7-9c854c9f17d7/

An alert is displayed from the player iframe. This alerts says that there is invalid response status code from the server : 500.

Is it possible to fix this in order to see / compare the old player?
Thanks !

**Comment by gnuletik** [comment]
Here's the error generated by the server

```
ImproperlyConfigured at /timeside/api/analysis/
Could not resolve URL for hyperlinked relationship using view name "subprocessor-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```

Maybe the server uses an older version impacted by this issue: https://github.com/Parisson/TimeSide/issues/178 ?

May we checkout on older version ?

**Comment by Tointoin** [comment]
I found out that current prod wasabi.telemeta.org is in `TimeSide-WASABI-test`. I pulled recent commits and problem is solved.

**Comment by gnuletik** [comment]
Thanks @Tointoin ! :)
