### ISSUE TITLE
[Schema/Docs] Add securityScheme to schema

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#189]
As we are now moving the API to JWT tokens, the schema need to be updated according to the change.

Following the [swagger docs](https://swagger.io/docs/specification/authentication/bearer-authentication/), we need to :
- [x] Add a `security` key at root level
- [x] Add a `securityScheme` key to the `components` objects

I already manually made the change inside the SDK and it seems to work as expected.
See https://github.com/Ircam-Web/timeside-sdk-js/commit/516064ef5033c4c811fb69cd2a8f53140639f6a0#diff-527e42f8a5bd34682a4175cdbfdee526

**Comment by Tointoin** [comment]
fixed. Pulled on sandbox.

**Comment by gnuletik** [comment]
Awesome ! Thanks for the fast answer & fix !

However, there's just a small typo : `bearerFomrat` instead of `bearerFormat`.
The rest works like a charm :)
