### ISSUE TITLE
[Schema/Docs] createTokenObtainPair should return an object with access and refresh keys

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#190]
In the schema, the routes handling the JWT tokens seems to have an invalid response schema.

#### createTokenObtainPair
In the schema, the `createTokenObtainPair` operation's response is an object with a `username` key.
See: https://sandbox.wasabi.telemeta.org/timeside/api/docs/#operation/createTokenObtainPair

However, it should be an object with a `refresh` and `access` key.

See
```
curl 'https://sandbox.wasabi.telemeta.org/timeside/api/token/' -X POST -H 'Content-Type: application/json' -d '{ "username": "XXX", "password": "XXX" }'
```
```json
{
   "refresh":"....",
   "access":"...."
}
```

#### createTokenRefresh

In the schema, the `createTokenRefresh` operation's response is an object with a `refresh` key.
See: https://sandbox.wasabi.telemeta.org/timeside/api/docs/#operation/createTokenRefresh

However, it should be an object with a `refresh` key.

```
curl -v 'https://sandbox.wasabi.telemeta.org/timeside/api/token/refresh/' -X POST -H 'Content-Type: application/json' -d '{ "refresh": "..." }
```
```json
{"access":"..."}
```

#### createTokenVerify
In the schema, the `createTokenVerify` operation's response is an object with a `token` key.
See: https://sandbox.wasabi.telemeta.org/timeside/api/docs/#operation/createTokenVerify 

However, it should be an empty object.

```
curl -v 'https://sandbox.wasabi.telemeta.org/timeside/api/token/verify/' -X POST -H 'Content-Type: application/json' -d '{ "token": "..." }
```
```json
{}
```

Would it be possible to update the schema ?
Thanks :)

**Comment by Tointoin** [comment]
Well, deeper it gets into schema objects harder it becomes to hardcode it with `CustomSchemaGenerator`. I will update it but it would be good to pull request DRF or schema generation `django-rest-framework-simplejwt`on this.

**Comment by Tointoin** [comment]
Should access be a boolean or a string?
