### ISSUE TITLE
[API] Create a testing user on sandbox for player's CI

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#192]
In order to run the automated tests on the player, would it be possible to create a testing user with limited access?

Currently, there's only one admin user and the credentials are available publicly in the tests.
It may be security concerns if we make a public release.

Also, it may be better if everyone creates a separate user.
What's your thoughts @Tointoin @yomguy ?

Thanks !

**Comment by yomguy** [comment]
Hi @gnuletik 
Yes, sure! I will send some credentials in a PM.
Do they really need to be public for the tests?

**Comment by gnuletik** [comment]
Hi @yomguy,
Thanks :)

No, you're right. We can store the test user credentials in Github Secrets. Then, they'll only be available to users with collaborator access on the repo.
It's an extra configuration for local environment but that's OK.

**Comment by gnuletik** [comment]
@yomguy,

I updated the tests in order to configure the timeside user in environment variables / Github Secrets.
https://github.com/Ircam-Web/timeside-player/commit/a142962c0cddb750a768a1426a03c76673426657

Can you reset the current password for the admin user ?

Thanks!

**Comment by yomguy** [comment]
@gnuletik @Tointoin 
new admin password sent as PM

**Comment by gnuletik** [comment]
Thanks @yomguy !
