### ISSUE TITLE
[API] `listAnnotations`  filter by annotation_track_uuid

### ISSUE THREAD

**Issue by gnuletik** [Parisson/TimeSide#196]
`listAnnotations` should have a query parameter called "track_uuid" to filter annotations by AnnotationTrack's UUID
See: https://sandbox.wasabi.telemeta.org/timeside/api/docs/#operation/listAnnotations

Thanks!

**Comment by Tointoin** [comment]
[on sandbox](https://sandbox.wasabi.telemeta.org/timeside/api/docs/#operation/listAnnotations) ✅
