### ISSUE TITLE
Problems installing in osx ~ "gobject missing"

### ISSUE THREAD

**Issue by vectorsize** [Parisson/TimeSide#45]
I've been trying to install timeside on my osx machine and I made it pretty far (after cumbersomely installing several dependencies).
Ive reached to a point where I can include timeside inside a python script, except now it complains about gobject missing.

Here is the thrown error:

```
import timeside
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "timeside/__init__.py", line 4, in <module>
    import core
  File "timeside/core.py", line 31, in <module>
    import gobject
ImportError: No module named gobject
```

I tried brew's libgobject, pygobject and gobject-introspection without any luck…
any ideas?

**Comment by yomguy** [comment]
This will be finally fixed with the docker image through the 0.8 release.

**Comment by SamridhiJ** [comment]
how to fix this in windows ... please help me out ..

**Comment by yomguy** [comment]
Hi @SamridhiJ,
please follow the new setup process thanks to docker-compose and not the old one.
