### ISSUE TITLE
Couldn't create 'uridecodebin' element

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#67]
Hi,

I get this error :

 File "/usr/local/lib/python2.7/dist-packages/TimeSide-0.6.1-py2.7.egg/timeside/decoder/utils.py", line 129, in get_media_uri_info
   uri_discoverer = Discoverer(GST_DISCOVER_TIMEOUT)

GError: Couldn't create 'uridecodebin' element

In the Apache logs :
(mod_wsgi:22224): GStreamer-CRITICAL **: gst_object_unref: assertion `object != NULL' failed

Thanks.

---
Anas
http://phonotheque.cmam.tn

**Comment by yomguy** [comment]
Hi Anas,
It seems Telemeta / TimeSide doesn't have access to the file or the file is corrupted.
Could you try a simple manual test with TimeSide like in the tuto ?
http://files.parisson.com/timeside/doc/tutorial/quick_start.html

**Comment by AnasGhrab** [comment]
Hi Yomguy,

It is ok now, TimeSide works. The problem seems to be the version of GStreamer..

Thanks.

**Comment by yomguy** [comment]
What's yours? The version needed for TS is 0.10 for now.

**Comment by AnasGhrab** [comment]
Yes.. I installed 0.10 and it was OK.

**Comment by yomguy** [comment]
good :)
