### ISSUE TITLE
Can't see Play/Stop buttons

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#68]
With the small view, I don't see the Play/Stop buttons. The menus are too long. What manages them ?

![capture d ecran 2015-01-18 a 13 15 09](https://cloud.githubusercontent.com/assets/2726240/5792334/2d3c7fdc-9f14-11e4-850c-cad7bb9e839c.png)

---
Anas
http://phonotheque.cmam.tn

**Comment by yomguy** [comment]
Some of the grapher names wre indeed too long. This has been fixed in the fresh bugfix release 0.6.2 ;)

**Comment by yomguy** [comment]
We know the grapher selector need to be placed somewhere else and it will be done. For now, one can access to all hidden buttons zooming the player to its full size, as the selector is floating right...
