### ISSUE TITLE
WebPlay embedding authentifiation

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#70]
Hi,

I'm trying to embed Web Players from an outside server.

1) The simplest way seems to be an iframe : 

<iframe width=900 height=260 frameborder=0 scrolling=no marginheight=0 marginwidth=0 src=http://phonotheque.cmam.tn/archives/items/aroussa2014_2/player/900x170></iframe>

It works when I'm logged in Telemeta through a user account. Is there a way to make the embedding with an authenticated access to make the Web Player publicly accessed ?

2) I've looked inside the https://github.com/Parisson/TimeSide/wiki/Ui-Guide. How to set the
soundManager.url = '/path/to/swfs/' to access a distant server ?

How to manage the authentification ?

Thanks,

---

Anas

**Comment by yomguy** [comment]
Hi Anas,
Sorry, I'm late on this..
If the player is embedded in a frame like does the tiny "</>" button on the player, the session will pass through the iframe. So, if you are not connected to the telemeta website, you will not be also in the iframe. 
We can change this public behavior by changing the item.access_type from "metadata" to "full". Note setting the same rule to the collection will override all the collection's items access rules.

**Comment by yomguy** [comment]
Re-reading your comments, I wonder if I really understand your need : a private resource would be playable publically through the iframe?

**Comment by AnasGhrab** [comment]
Yes, it's that. You gave me the answer...
