### ISSUE TITLE
Question : what is the longest file TimeSide can read ?

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#75]
If we read long files (about one hour), sometimes we have to wait, wait... Other times it does not read. Is that normal ?

**Comment by yomguy** [comment]
No limit to file length for TimeSide thanks to its streaming engine architecture. This is the case for simple analyzers or graphers but it can take time of course for special cases.. For very large files and complex analyzer (with a lot of post-processing), the RAM can overload of course.
Could you try you processing manually outside Telemeta?

**Comment by AnasGhrab** [comment]
"Could you try you processing manually outside Telemeta?"

What are processes done by TimeSide when we read a file ?

**Comment by yomguy** [comment]
Just decoding (for the decoder) to buffer and/or to a stack in memory.

**Comment by AnasGhrab** [comment]
So, I have to do these commands for the long file to be easily read ?
 
```
from timeside.core import get_processor
wavfile = "/path/to/the/wav/file"
FileDecoder  =  get_processor('file_decoder')
decoder = FileDecoder(uri=wavfile)
decoder.run()
```

**Comment by yomguy** [comment]
Some doc to get the stack running:
http://files.parisson.com/timeside/doc/tutorials/frames_stack.html
