### ISSUE TITLE
TimeSide==0.8 (dev) + Telemeta 1.5.2 (dev) : Can't play files

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#76]
Reading audio files is not possible. It is always loading. It works well with Telemeta 1.5.1 + TimeSide==0.8 (dev), but not using Telemeta 1.5.2 (dev).

**Comment by yomguy** [comment]
If there's a bug here, you should have something to report requiring the MP3 file itself. 
For example http://archives.crem-cnrs.fr/archives/items/download/CNRSMH_E_1997_022_001_05.mp3 Use your own domain and code ;)

**Comment by AnasGhrab** [comment]
I still have this problem. The .mp3 was downloads and works.

**Comment by yomguy** [comment]
You mean you can download it but not play it though the player ?

**Comment by AnasGhrab** [comment]
Yes. Through the player it « turns, turns, ...» without showing anything...

**Comment by AnasGhrab** [comment]
![capture d ecran 2015-09-05 a 10 20 35](https://cloud.githubusercontent.com/assets/2726240/9698636/d791d0ba-53b7-11e5-94fd-f7862cb80cfe.png)

**Comment by AnasGhrab** [comment]
The browser gives me this : 
```
http://phonotheque.cmam.tn/static/timeside/lib/sm2/soundmanager2-nodebug-jsmin.js Failed to load resource: the server responded with a status of 404 (Not Found)
phonotheque.cmam.tn/:83 Uncaught ReferenceError: soundManager is not defined
```

**Comment by yomguy** [comment]
OK, this means you need to be sure that timeside.player is in the INSTALLED_APPS list and then do:
```
python manage.py collectstatic
```

**Comment by AnasGhrab** [comment]
Yes ! It's ok now :) Thank you !

**Comment by yomguy** [comment]
Cool :-)
