### ISSUE TITLE
Question : Where the data of the analysis is stored ?

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#78]
When a file is analyzed, for the f0 for example, is the data (the list of frequencies) stored somewhere ?

Thx.

**Comment by yomguy** [comment]
Yes, all data are automatically stored in a HDF5 file container as demonstrated and specified here:
http://nbviewer.ipython.org/github/thomasfillon/Timeside-demos/tree/master/
http://files.parisson.com/timeside/doc/tutorial/AnalyzerResult.htmlut

But it is missing a explicit documentation about how we can also save, load and serialize from / into JSON, XML and HDF5 formats....

**Comment by AnasGhrab** [comment]
Thanks !
