### ISSUE TITLE
Analyzer from the Essentia library

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#79]
Is it planned to add other external libraries ? Essentia for example ?

Yaafe is still not so easy to install (at least on Mac...)...

**Comment by yomguy** [comment]
Yes, it has been discussed but not planned yet for Essentia. But the MIR toolbox ported to python is on the road thanks to the DIADEMS project. Right @thomasfillon ?

**Comment by thomasfillon** [comment]
Hi !
The Timbre Toolbox integration is on development (See Geoffroy Peeters, Bruno Giordano, Patrick Susini, Nicolas Misdariis, Stephen Mcadams. The Timbre Toolbox: Audio descriptors of musical signals. JASA, 2011, 5 (130). ).

@AnasGhrab : What kind of audio features do you  need ?

**Comment by AnasGhrab** [comment]
@thomasfillon : the Melodia algorithm for pitch extraction : PredominantMelody().

**Comment by yomguy** [comment]
I must say here that aubio, VAMP and yafee have been already linked:
https://github.com/Parisson/TimeSide/tree/master/timeside/plugins/analyzer/externals

**Comment by yomguy** [comment]
As the initial question has been solved, I rewrite it to focus on Essentia especially. Maybe we need a few more for librosa and others..

**Comment by thomasfillon** [comment]
This will be developed as part of the Dacaryh project.

**Comment by AnasGhrab** [comment]
About the Dacaryh project : http://archives.crem-cnrs.fr/archives/fonds/CNRSMH_DACARYH/

**Comment by yomguy** [comment]
Essentia integration done
