### ISSUE TITLE
Question: Key Detection

### ISSUE THREAD

**Issue by duro** [Parisson/TimeSide#86]
I am starting a project which will look to take uploaded files, analyze them for their musical key, and then write that metadata to the file and a database. Is this library capable of that? Any pointers in the right direction would be very much appreciated.

**Comment by yomguy** [comment]
Hi @duro 
Yes TimeSide can do this thanks to the aubio_pitch plugin
https://github.com/Parisson/TimeSide/blob/master/timeside/plugins/analyzer/externals/aubio_pitch.py

Please first try to install and check the documentation about how to analyze your data. Some news will soon give you the opportunity to write the results in a database, but you can save them to a single for the moment.
