### ISSUE TITLE
ValueError: input size of pitch should be 1024, not 2048

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/TimeSide#96]
```
import timeside
from timeside.core.tools.test_samples import samples
from timeside.core import get_processor
decoder = get_processor('file_decoder')(samples["sweep.wav"])
pitch = get_processor('aubio_pitch')()
pipe = decoder | pitch
pipe.run()
```

I get : 

```
ValueErrorTraceback (most recent call last)
<ipython-input-27-fc1f59af2fce> in <module>()
      5 pitch = get_processor('aubio_pitch')()
      6 pipe = decoder | pitch
----> 7 pipe.run()

/usr/local/lib/python2.7/dist-packages/TimeSide-0.8.1-py2.7.egg/timeside/core/processor.pyc in run(self, channels, samplerate, blocksize)
    492             frames, eod = source.process()
    493             for item in items:
--> 494                 frames, eod = item.process(frames, eod)
    495 
    496         if source.id() == 'live_decoder':

/usr/local/lib/python2.7/dist-packages/TimeSide-0.8.1-py2.7.egg/timeside/core/preprocessors.pyc in wrapper(analyzer, frames, eod)
     72             downmix_frames = frames
     73         # Processing
---> 74         process_func(analyzer, downmix_frames, eod)
     75 
     76         return frames, eod

/usr/local/lib/python2.7/dist-packages/TimeSide-0.8.1-py2.7.egg/timeside/core/preprocessors.pyc in wrapper(analyzer, frames, eod)
    174         # Processing
    175         for adapted_frames, adapted_eod in analyzer.frames_buffer.frames(frames, eod):
--> 176             process_func(analyzer, adapted_frames, adapted_eod)
    177 
    178         return frames, eod

/usr/local/lib/python2.7/dist-packages/TimeSide-0.8.1-py2.7.egg/timeside/plugins/analyzer/externals/aubio_pitch.pyc in process(self, frames, eod)
    108     def process(self, frames, eod=False):
    109         #time = self.block_read * self.input_stepsize * 1. / self.samplerate()
--> 110         self.pitches += [self.aubio_pitch(frames)[0]]
    111         self.pitch_confidences += [self.aubio_pitch.get_confidence()]
    112         self.block_read += 1

ValueError: input size of pitch should be 1024, not 2048
```

**Comment by piem** [comment]
hi!

A quick check shows that all other aubio plugins are broken. It may be that this bug was existing and affecting the results when using aubio < 0.4.4 since aubio now checks the size of the input vectors.

I tried checking how other plugins work, for instance `spectrogram.py`, but i get a `frame.shape` of length `step_blocksize` in `process` when setting it up like this:

```python
proc = get_processor('spectrogram_analyzer')(input_blocksize=2048, input_stepsize=1024)
```

even though the `@frames_adapter` decorator is there.

@thomasfillon any idea what is going on there?

A quick workaround to make it run (but with a large stepsize):
```python
blocksize_s = 4096/44100.                                                                       
pitch = get_processor('aubio_pitch')(blocksize_s=blocksize_s, stepsize_s=blocksize_s)     
```
cheers, piem

**Comment by piem** [comment]
hello!

any news on this?

thanks, piem

**Comment by thomasfillon** [comment]
Hi Piem,

I try to understand the problem. 

> aubio now checks the size of the input vectors.
What does it mean exactly ? What are the valid values for input size ? 

Does it mean that Aubio Pitch what setup for a block size of 1024 but receive a frame of 2048 samples ?
(like if something is wrong with stereo handling)

**Comment by piem** [comment]
hi @thomasfillon! :)

yes, it seems that's what is going on. i'm not sure it is related to the number of channels in the file though.

**Comment by thomasfillon** [comment]
Ok I will investigate the frame size during process and give a special attention to the `@frames_adapter` and `@downmix_to_mon`o decorator there.

Thank you !

**Comment by thomasfillon** [comment]
Hi @piem 

The initialization of Aubio Pitch is done like this: https://github.com/Parisson/TimeSide/blob/master/timeside/plugins/analyzer/externals/aubio_pitch.py#L72
```
        self.aubio_pitch = pitch("default", self.input_blocksize, self.input_stepsize, samplerate)
```

Has something changed in the pitch function call ?
If I use the following configuration : 
```
from aubio import pitch
import numpy as np
ap = pitch("default", 2048, 1024, 44100)

frame_1024 = np.random.randn(1024).astype(np.float32)
frame_2048 = np.random.randn(2048).astype(np.float32)

```
I get 
```
In [32]: ap(frame_1024)
Out[32]: array([ 0.], dtype=float32)

In [33]: ap(frame_2048)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-81c5b0d3d915> in <module>()
----> 1 ap(frame_2048)

ValueError: input size of pitch should be 1024, not 2048
```

**Comment by thomasfillon** [comment]
ok I think I understand

pitch() is waiting for a frame of length the hopsize (stepsize) and not a blocksize length frame.
That's it ?

**Comment by piem** [comment]
hi @thomasfillon 

yes, that's it. What changed in 0.4.4 is that when processing an input vector, the length of that vector is checked for.

the same is true for all aubio algorithms: `buf_size` or `win_size` is used to adjust the length of the the analysis window, while `hop_size` is used to adjust the number of frames between two consecutive analysis.
