### ISSUE TITLE
How standalone is the player ?

### ISSUE THREAD

**Issue by Numerizen** [Parisson/TimeSide#98]
Hi and thanks for your work on this project.

My question is straightforward : is the player really usable without all the fancy sound analysis stuff TimeSide provides ?

I would like to use the great functionality the player provides, but can't afford to install and code all the necessary software intended to be used serverside.

I saw this issue https://github.com/Parisson/TimeSide/issues/56 which is closed but doesn't seem really answered, and which is very old, so I wanted to get some fresh information on this matter.

Hope to read from you soon. Thanks for reading.

**Comment by thomasfillon** [comment]
HI !
Thanks for your question. To be able to give you a relevant answer I need to fully understand your needs.

Do you mean you only want front-end stuff on the client side and nothing from the server ?
What are precisely the functionalities you are interested in ?

**Comment by Numerizen** [comment]
I would like the player and nothing else if possible, so yes, frontend and no backend. 

My users want all the graphs and the marker stuff, at least, but anything I didn't discover on the frontend could be interesting. And of course the basic player functionalities : play, end of track, begining of track, etc. as well as the file information.

**Comment by thomasfillon** [comment]
I'm sorry with the current code it is not possible to get the player without the back-end.
We rely on the back-end to compute all the graphs and to store the markers data. We also rely on the back-end to provide the audio in the proper format for the browser.

As the player can be embed in a iframe and as we are developing an API dedicated to provide the player at the front-end everything he needs from the server, if you don't want to deal with the back-end you could delegate it. We could manage a server which provide the API to the front-end as a service.

Another approach would be to move some of the back-end functionalities into the front-end but that would require a lot of development.

**Comment by Numerizen** [comment]
Yes, the development is not an option, nor is the delegation, because of project funds.

I guess I'll try to manage a server side setup of all the required stuff, but I didn't understand yet how the player talks to the server.  Back to documentation I guess, but if you have a starting point to share and a few minutes to tell me about it, feel free ;-).

Anyway, thanks a lot for your clear and quick answers. It saved me a lot of time.

**Comment by Numerizen** [comment]
Folow up on this issue : I managed to install a Telemeta docker image and embed the player on another website with the built-in icon (in an iframe) which could do the trick. It doesn't pull the file info and the bookmarks' details though, which is unfortunate.

I tried to look at the Telemeta code to see if I could borrow some to call TimeSide directly in PHP, but unfortunately the whole thing is coded in Python, so no joy for me here.

Ideally, I could  manage the sound files in the CMS we're using, and call the player from my PHP code - i.e : replace Telemeta with our own application and let TimeSide handle all the conversion and analysis work.

If there is any way to do this, could you hint me about it ? 

Thanks in advance.

**Comment by thomasfillon** [comment]
Hi !

If you need the markers, then you also need to get the players from a Telemeta instance. 
This would change in the next major release of Timeside but you would still need to have and server side instance of Timeside running to manage the database and compute the data display.

**Comment by Numerizen** [comment]
OK, thanks.

So I understand TimeSide as is, except for very specialized uses, is very bound to Telemeta. I'll see what the project manager decides and act accordingly.

Having to only use TimeSide without Telemeta would be a lot lighter though. Any clue when the next major release will happen ?

**Comment by thomasfillon** [comment]
Yes for now Timeside is very bound to Telemeta as it was extracted from Telemeta. 
However, its current capabilities now go beyond the Telemeta needs and the goal is to make Timeside server and Timeside web player independent of Telemeta.

That being said some web related features of Timeside have not been completely extracted from Telemeta yet.

The next major release will cover many new improvments : zoom along the time axis, annotations capabilities (enhancement of current markers), REST API, ..., and suppress the need to rely on Telemeta to get the player fully functional.
That is a lot a job and we are looking for some fundings to help this open-source project to reach this milestone. If everything is fine it should be available this summer.
Do not hesitate to contact us directly (see email address @parisson in the code) to exchange more precisely about your needs and requirements.

**Comment by Numerizen** [comment]
I'm sure it's a ton of work, no doubt about that. 

Your answers gave me certainty about what we can expect from Timeside. Whether we'll use it or not is out of my hands though but I'll make sure to let you know if the project chooses to adopt it.

Thanks again for your time.

**Comment by thomasfillon** [comment]
Hi @Numerizen 

I close the issue. 
Feel free to reopen it if you need to or if you have some news about your project and your choices about using Timeside.
